"""Add delete functionality for conversation history

Revision ID: 5bdf4016a05f
Revises: 25a55e895e25
Create Date: 2026-03-24 16:17:11.813794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdf4016a05f'
down_revision: Union[str, Sequence[str], None] = '25a55e895e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_deleted')
    # ### end Alembic commands ###
